AllCops:
  NewCops: enable
  Include:
    - 'Gemfile'
    - 'Rakefile'
  Exclude:
    - 'vendor/**/*'

Metrics/ClassLength:
  Enabled: false

Style/Documentation:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Style/Alias:
  Enabled: false

Layout/FirstArrayElementIndentation:
  Enabled: false

Style/HashSyntax:
  EnforcedStyle: ruby19

Layout/LineLength:
  Max: 120

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*.rb'

Metrics/ModuleLength:
  CountComments: false  # count full line comments?
  Max: 200

Style/CommentAnnotation:
  Keywords:
    - TODO
    - FIXME
    - OPTIMIZE
    - HACK
    - REVIEW

inherit_from: .rubocop_todo.yml
