---
language: ruby
sudo: false
dist: trusty
rvm:
  - 2.4.0
  - 2.3.3
  - 2.2.6
  - 2.1
branches:
  only: [master]
env:
  - COMMAND=rake
matrix:
  include:
    - rvm: 2.4.0
      env: COMMAND=rubocop
before_install:
  - gem uninstall -v '>= 2' -i $(rvm gemdir)@global -ax bundler || true
  - gem install bundler -v '< 2'
  - bundle install
script:
  - bundle exec $COMMAND
cache: bundler
