---
language: ruby
sudo: false
dist: trusty
rvm:
  - 2.4.0
  - 2.3.3
  - 2.2.6
  - 2.1
branches:
  only: [master]
env:
  - COMMAND=rake
before_install:
  - gem update --system
  - gem install bundler
matrix:
  include:
    - rvm: 2.4.0
      env: COMMAND=rubocop
script:
  - bundle exec $COMMAND
cache: bundler
